name: assignment_client
description: Flutter assignment for PokerLab recruitment process.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  freezed_annotation: 2.2.0
  grpc: 3.2.2
  json_annotation: 4.8.1
  protobuf: 3.0.0
  provider: 6.0.5

  cupertino_icons: 1.0.2

dev_dependencies:
  build_runner: 2.3.3
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  json_serializable: 6.6.2

flutter:
  uses-material-design: true
